"""add_updated_at_to_folders

Revision ID: 675de9f0d3c6
Revises: f6d920f5a664
Create Date: 2025-07-29 06:46:48.756887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675de9f0d3c6'
down_revision: Union[str, None] = 'f6d920f5a664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'updated_at')
    # ### end Alembic commands ###
