"""add_semester_and_course_models

Revision ID: f6d920f5a664
Revises: f5fb399402d8
Create Date: 2025-07-28 04:42:53.972503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d920f5a664'
down_revision: Union[str, None] = 'f5fb399402d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_course_semester', 'courses', ['semester_id'], unique=False)
    op.create_index('idx_course_unique_code', 'courses', ['user_id', 'semester_id', 'code'], unique=True)
    op.create_index('idx_course_user_semester', 'courses', ['user_id', 'semester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_course_user_semester', table_name='courses')
    op.drop_index('idx_course_unique_code', table_name='courses')
    op.drop_index('idx_course_semester', table_name='courses')
    op.drop_column('courses', 'updated_at')
    # ### end Alembic commands ###
